userAssets=[
  {"d":"audio",
   "f":[
    "female-tiring-day.ogg",
    "footstep_carpet_000.ogg",
    "Hello.ogg",
    "short-intro.ogg",
    "soft-music-small-mono.ogg",
    "waterwheel.ogg"
  ]},
  {"d":"curated",
   "f":[
    {"d":"characters",
     "f":[
      {"d":"female-avatar",
       "f":[
        "female-avatar.babylon",
        "thumbnail.png"
      ]},
      {"d":"male-avatar",
       "f":[
        "male-avatar.babylon",
        "thumbnail.png"
      ]}
    ]},
    {"d":"fantasy-town-fountains",
     "f":[
      {"d":"fountainCenter",
       "f":[
        "fountainCenter.mtl",
        "fountainCenter.obj",
        "thumbnail.png"
      ]},
      {"d":"fountainCorner",
       "f":[
        "fountainCorner.mtl",
        "fountainCorner.obj",
        "thumbnail.png"
      ]},
      {"d":"fountainCornerInner",
       "f":[
        "fountainCornerInner.mtl",
        "fountainCornerInner.obj",
        "thumbnail.png"
      ]},
      {"d":"fountainCornerInnerSquare",
       "f":[
        "fountainCornerInnerSquare.mtl",
        "fountainCornerInnerSquare.obj",
        "thumbnail.png"
      ]},
      {"d":"fountainCurved",
       "f":[
        "fountainCurved.mtl",
        "fountainCurved.obj",
        "thumbnail.png"
      ]},
      {"d":"fountainEdge",
       "f":[
        "fountainEdge.mtl",
        "fountainEdge.obj",
        "thumbnail.png"
      ]},
      {"d":"fountainRound",
       "f":[
        "fountainRound.mtl",
        "fountainRound.obj",
        "thumbnail.png"
      ]},
      {"d":"fountainRoundDetail",
       "f":[
        "fountainRoundDetail.mtl",
        "fountainRoundDetail.obj",
        "thumbnail.png"
      ]},
      {"d":"fountainSquare",
       "f":[
        "fountainSquare.mtl",
        "fountainSquare.obj",
        "thumbnail.png"
      ]},
      {"d":"fountainSquareDetail",
       "f":[
        "fountainSquareDetail.mtl",
        "fountainSquareDetail.obj",
        "thumbnail.png"
      ]}
    ]},
    {"d":"fantasy-town-roads",
     "f":[
      {"d":"road",
       "f":[
        "road.mtl",
        "road.obj",
        "thumbnail.png"
      ]},
      {"d":"roadBend",
       "f":[
        "roadBend.mtl",
        "roadBend.obj",
        "thumbnail.png"
      ]},
      {"d":"roadCorner",
       "f":[
        "roadCorner.mtl",
        "roadCorner.obj",
        "thumbnail.png"
      ]},
      {"d":"roadCornerInner",
       "f":[
        "roadCornerInner.mtl",
        "roadCornerInner.obj",
        "thumbnail.png"
      ]},
      {"d":"roadCurb",
       "f":[
        "roadCurb.mtl",
        "roadCurb.obj",
        "thumbnail.png"
      ]},
      {"d":"roadEdge",
       "f":[
        "roadEdge.mtl",
        "roadEdge.obj",
        "thumbnail.png"
      ]},
      {"d":"roadEdgeSlope",
       "f":[
        "roadEdgeSlope.mtl",
        "roadEdgeSlope.obj",
        "thumbnail.png"
      ]},
      {"d":"roadSlope",
       "f":[
        "roadSlope.mtl",
        "roadSlope.obj",
        "thumbnail.png"
      ]}
    ]},
    {"d":"fantasy-town-roofs",
     "f":[
      {"d":"roof",
       "f":[
        "roof.mtl",
        "roof.obj",
        "thumbnail.png"
      ]},
      {"d":"roofCorner",
       "f":[
        "roofCorner.mtl",
        "roofCorner.obj",
        "thumbnail.png"
      ]},
      {"d":"roofCornerInner",
       "f":[
        "roofCornerInner.mtl",
        "roofCornerInner.obj",
        "thumbnail.png"
      ]},
      {"d":"roofCornerRound",
       "f":[
        "roofCornerRound.mtl",
        "roofCornerRound.obj",
        "thumbnail.png"
      ]},
      {"d":"roofFlat",
       "f":[
        "roofFlat.mtl",
        "roofFlat.obj",
        "thumbnail.png"
      ]},
      {"d":"roofGable",
       "f":[
        "roofGable.mtl",
        "roofGable.obj",
        "thumbnail.png"
      ]},
      {"d":"roofGableDetail",
       "f":[
        "roofGableDetail.mtl",
        "roofGableDetail.obj",
        "thumbnail.png"
      ]},
      {"d":"roofGableEnd",
       "f":[
        "roofGableEnd.mtl",
        "roofGableEnd.obj",
        "thumbnail.png"
      ]},
      {"d":"roofGableTop",
       "f":[
        "roofGableTop.mtl",
        "roofGableTop.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHigh",
       "f":[
        "roofHigh.mtl",
        "roofHigh.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHighCorner",
       "f":[
        "roofHighCorner.mtl",
        "roofHighCorner.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHighCornerInner",
       "f":[
        "roofHighCornerInner.mtl",
        "roofHighCornerInner.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHighCornerRound",
       "f":[
        "roofHighCornerRound.mtl",
        "roofHighCornerRound.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHighFlat",
       "f":[
        "roofHighFlat.mtl",
        "roofHighFlat.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHighGable",
       "f":[
        "roofHighGable.mtl",
        "roofHighGable.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHighGableDetail",
       "f":[
        "roofHighGableDetail.mtl",
        "roofHighGableDetail.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHighGableEnd",
       "f":[
        "roofHighGableEnd.mtl",
        "roofHighGableEnd.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHighGableTop",
       "f":[
        "roofHighGableTop.mtl",
        "roofHighGableTop.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHighLeft",
       "f":[
        "roofHighLeft.mtl",
        "roofHighLeft.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHighPoint",
       "f":[
        "roofHighPoint.mtl",
        "roofHighPoint.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHighRight",
       "f":[
        "roofHighRight.mtl",
        "roofHighRight.obj",
        "thumbnail.png"
      ]},
      {"d":"roofHighWindow",
       "f":[
        "roofHighWindow.mtl",
        "roofHighWindow.obj",
        "thumbnail.png"
      ]},
      {"d":"roofLeft",
       "f":[
        "roofLeft.mtl",
        "roofLeft.obj",
        "thumbnail.png"
      ]},
      {"d":"roofPoint",
       "f":[
        "roofPoint.mtl",
        "roofPoint.obj",
        "thumbnail.png"
      ]},
      {"d":"roofRight",
       "f":[
        "roofRight.mtl",
        "roofRight.obj",
        "thumbnail.png"
      ]},
      {"d":"roofWindow",
       "f":[
        "roofWindow.mtl",
        "roofWindow.obj",
        "thumbnail.png"
      ]}
    ]},
    {"d":"fantasy-town-stairs",
     "f":[
      {"d":"stairsStone",
       "f":[
        "stairsStone.mtl",
        "stairsStone.obj",
        "thumbnail.png"
      ]},
      {"d":"stairsStoneCorner",
       "f":[
        "stairsStoneCorner.mtl",
        "stairsStoneCorner.obj",
        "thumbnail.png"
      ]},
      {"d":"stairsStoneHandrail",
       "f":[
        "stairsStoneHandrail.mtl",
        "stairsStoneHandrail.obj",
        "thumbnail.png"
      ]},
      {"d":"stairsStoneRound",
       "f":[
        "stairsStoneRound.mtl",
        "stairsStoneRound.obj",
        "thumbnail.png"
      ]},
      {"d":"stairsWood",
       "f":[
        "stairsWood.mtl",
        "stairsWood.obj",
        "thumbnail.png"
      ]},
      {"d":"stairsWoodHandrail",
       "f":[
        "stairsWoodHandrail.mtl",
        "stairsWoodHandrail.obj",
        "thumbnail.png"
      ]}
    ]},
    {"d":"fantasy-town-structures",
     "f":[
      {"d":"bannerGreen",
       "f":[
        "bannerGreen.mtl",
        "bannerGreen.obj",
        "thumbnail.png"
      ]},
      {"d":"bannerRed",
       "f":[
        "bannerRed.mtl",
        "bannerRed.obj",
        "thumbnail.png"
      ]},
      {"d":"blade",
       "f":[
        "blade.mtl",
        "blade.obj",
        "thumbnail.png"
      ]},
      {"d":"cart",
       "f":[
        "cart.mtl",
        "cart.obj",
        "thumbnail.png"
      ]},
      {"d":"cartHigh",
       "f":[
        "cartHigh.mtl",
        "cartHigh.obj",
        "thumbnail.png"
      ]},
      {"d":"chimney",
       "f":[
        "chimney.mtl",
        "chimney.obj",
        "thumbnail.png"
      ]},
      {"d":"chimneyBase",
       "f":[
        "chimneyBase.mtl",
        "chimneyBase.obj",
        "thumbnail.png"
      ]},
      {"d":"chimneyTop",
       "f":[
        "chimneyTop.mtl",
        "chimneyTop.obj",
        "thumbnail.png"
      ]},
      {"d":"lantern",
       "f":[
        "lantern.mtl",
        "lantern.obj",
        "thumbnail.png"
      ]},
      {"d":"overhang",
       "f":[
        "overhang.mtl",
        "overhang.obj",
        "thumbnail.png"
      ]},
      {"d":"pillarStone",
       "f":[
        "pillarStone.mtl",
        "pillarStone.obj",
        "thumbnail.png"
      ]},
      {"d":"pillarWood",
       "f":[
        "pillarWood.mtl",
        "pillarWood.obj",
        "thumbnail.png"
      ]},
      {"d":"planks",
       "f":[
        "planks.mtl",
        "planks.obj",
        "thumbnail.png"
      ]},
      {"d":"planksHalf",
       "f":[
        "planksHalf.mtl",
        "planksHalf.obj",
        "thumbnail.png"
      ]},
      {"d":"planksOpening",
       "f":[
        "planksOpening.mtl",
        "planksOpening.obj",
        "thumbnail.png"
      ]},
      {"d":"poles",
       "f":[
        "poles.mtl",
        "poles.obj",
        "thumbnail.png"
      ]},
      {"d":"polesHorizontal",
       "f":[
        "polesHorizontal.mtl",
        "polesHorizontal.obj",
        "thumbnail.png"
      ]},
      {"d":"stall",
       "f":[
        "stall.mtl",
        "stall.obj",
        "thumbnail.png"
      ]},
      {"d":"stallBench",
       "f":[
        "stallBench.mtl",
        "stallBench.obj",
        "thumbnail.png"
      ]},
      {"d":"stallGreen",
       "f":[
        "stallGreen.mtl",
        "stallGreen.obj",
        "thumbnail.png"
      ]},
      {"d":"stallRed",
       "f":[
        "stallRed.mtl",
        "stallRed.obj",
        "thumbnail.png"
      ]},
      {"d":"stallStool",
       "f":[
        "stallStool.mtl",
        "stallStool.obj",
        "thumbnail.png"
      ]},
      {"d":"watermill",
       "f":[
        "thumbnail.png",
        "watermill.mtl",
        "watermill.obj"
      ]},
      {"d":"wheel",
       "f":[
        "thumbnail.png",
        "wheel.mtl",
        "wheel.obj"
      ]},
      {"d":"windmill",
       "f":[
        "thumbnail.png",
        "windmill.mtl",
        "windmill.obj"
      ]}
    ]},
    {"d":"fantasy-town-terrain",
     "f":[
      {"d":"fence",
       "f":[
        "fence.mtl",
        "fence.obj",
        "thumbnail.png"
      ]},
      {"d":"fenceBroken",
       "f":[
        "fenceBroken.mtl",
        "fenceBroken.obj",
        "thumbnail.png"
      ]},
      {"d":"fenceCurved",
       "f":[
        "fenceCurved.mtl",
        "fenceCurved.obj",
        "thumbnail.png"
      ]},
      {"d":"fenceGate",
       "f":[
        "fenceGate.mtl",
        "fenceGate.obj",
        "thumbnail.png"
      ]},
      {"d":"hedge",
       "f":[
        "hedge.mtl",
        "hedge.obj",
        "thumbnail.png"
      ]},
      {"d":"hedgeCurved",
       "f":[
        "hedgeCurved.mtl",
        "hedgeCurved.obj",
        "thumbnail.png"
      ]},
      {"d":"hedgeGate",
       "f":[
        "hedgeGate.mtl",
        "hedgeGate.obj",
        "thumbnail.png"
      ]},
      {"d":"rockLarge",
       "f":[
        "rockLarge.mtl",
        "rockLarge.obj",
        "thumbnail.png"
      ]},
      {"d":"rockSmall",
       "f":[
        "rockSmall.mtl",
        "rockSmall.obj",
        "thumbnail.png"
      ]},
      {"d":"rockWide",
       "f":[
        "rockWide.mtl",
        "rockWide.obj",
        "thumbnail.png"
      ]},
      {"d":"tree",
       "f":[
        "thumbnail.png",
        "tree.mtl",
        "tree.obj"
      ]},
      {"d":"treeCrooked",
       "f":[
        "thumbnail.png",
        "treeCrooked.mtl",
        "treeCrooked.obj"
      ]},
      {"d":"treeHigh",
       "f":[
        "thumbnail.png",
        "treeHigh.mtl",
        "treeHigh.obj"
      ]},
      {"d":"treeHighCrooked",
       "f":[
        "thumbnail.png",
        "treeHighCrooked.mtl",
        "treeHighCrooked.obj"
      ]},
      {"d":"treeHighRound",
       "f":[
        "thumbnail.png",
        "treeHighRound.mtl",
        "treeHighRound.obj"
      ]}
    ]},
    {"d":"fantasy-town-walls",
     "f":[
      {"d":"wall",
       "f":[
        "thumbnail.png",
        "wall.mtl",
        "wall.obj"
      ]},
      {"d":"wallArch",
       "f":[
        "thumbnail.png",
        "wallArch.mtl",
        "wallArch.obj"
      ]},
      {"d":"wallArchTop",
       "f":[
        "thumbnail.png",
        "wallArchTop.mtl",
        "wallArchTop.obj"
      ]},
      {"d":"wallArchTopDetail",
       "f":[
        "thumbnail.png",
        "wallArchTopDetail.mtl",
        "wallArchTopDetail.obj"
      ]},
      {"d":"wallBlock",
       "f":[
        "thumbnail.png",
        "wallBlock.mtl",
        "wallBlock.obj"
      ]},
      {"d":"wallBlockHalf",
       "f":[
        "thumbnail.png",
        "wallBlockHalf.mtl",
        "wallBlockHalf.obj"
      ]},
      {"d":"wallBroken",
       "f":[
        "thumbnail.png",
        "wallBroken.mtl",
        "wallBroken.obj"
      ]},
      {"d":"wallCorner",
       "f":[
        "thumbnail.png",
        "wallCorner.mtl",
        "wallCorner.obj"
      ]},
      {"d":"wallCornerDetail",
       "f":[
        "thumbnail.png",
        "wallCornerDetail.mtl",
        "wallCornerDetail.obj"
      ]},
      {"d":"wallCornerDiagonal",
       "f":[
        "thumbnail.png",
        "wallCornerDiagonal.mtl",
        "wallCornerDiagonal.obj"
      ]},
      {"d":"wallCornerDiagonalHalf",
       "f":[
        "thumbnail.png",
        "wallCornerDiagonalHalf.mtl",
        "wallCornerDiagonalHalf.obj"
      ]},
      {"d":"wallCornerEdge",
       "f":[
        "thumbnail.png",
        "wallCornerEdge.mtl",
        "wallCornerEdge.obj"
      ]},
      {"d":"wallCurved",
       "f":[
        "thumbnail.png",
        "wallCurved.mtl",
        "wallCurved.obj"
      ]},
      {"d":"wallDetailCross",
       "f":[
        "thumbnail.png",
        "wallDetailCross.mtl",
        "wallDetailCross.obj"
      ]},
      {"d":"wallDetailDiagonal",
       "f":[
        "thumbnail.png",
        "wallDetailDiagonal.mtl",
        "wallDetailDiagonal.obj"
      ]},
      {"d":"wallDetailHorizontal",
       "f":[
        "thumbnail.png",
        "wallDetailHorizontal.mtl",
        "wallDetailHorizontal.obj"
      ]},
      {"d":"wallDiagonal",
       "f":[
        "thumbnail.png",
        "wallDiagonal.mtl",
        "wallDiagonal.obj"
      ]},
      {"d":"wallDoor",
       "f":[
        "thumbnail.png",
        "wallDoor.mtl",
        "wallDoor.obj"
      ]},
      {"d":"wallDoorwayBase",
       "f":[
        "thumbnail.png",
        "wallDoorwayBase.mtl",
        "wallDoorwayBase.obj"
      ]},
      {"d":"wallDoorwayRound",
       "f":[
        "thumbnail.png",
        "wallDoorwayRound.mtl",
        "wallDoorwayRound.obj"
      ]},
      {"d":"wallDoorwaySquare",
       "f":[
        "thumbnail.png",
        "wallDoorwaySquare.mtl",
        "wallDoorwaySquare.obj"
      ]},
      {"d":"wallDoorwaySquareWide",
       "f":[
        "thumbnail.png",
        "wallDoorwaySquareWide.mtl",
        "wallDoorwaySquareWide.obj"
      ]},
      {"d":"wallDoorwaySquareWideCurved",
       "f":[
        "thumbnail.png",
        "wallDoorwaySquareWideCurved.mtl",
        "wallDoorwaySquareWideCurved.obj"
      ]},
      {"d":"wallHalf",
       "f":[
        "thumbnail.png",
        "wallHalf.mtl",
        "wallHalf.obj"
      ]},
      {"d":"wallRounded",
       "f":[
        "thumbnail.png",
        "wallRounded.mtl",
        "wallRounded.obj"
      ]},
      {"d":"wallSide",
       "f":[
        "thumbnail.png",
        "wallSide.mtl",
        "wallSide.obj"
      ]},
      {"d":"wallSlope",
       "f":[
        "thumbnail.png",
        "wallSlope.mtl",
        "wallSlope.obj"
      ]},
      {"d":"wallWindowGlass",
       "f":[
        "thumbnail.png",
        "wallWindowGlass.mtl",
        "wallWindowGlass.obj"
      ]},
      {"d":"wallWindowRound",
       "f":[
        "thumbnail.png",
        "wallWindowRound.mtl",
        "wallWindowRound.obj"
      ]},
      {"d":"wallWindowShutters",
       "f":[
        "thumbnail.png",
        "wallWindowShutters.mtl",
        "wallWindowShutters.obj"
      ]},
      {"d":"wallWindowSmall",
       "f":[
        "thumbnail.png",
        "wallWindowSmall.mtl",
        "wallWindowSmall.obj"
      ]},
      {"d":"wallWindowStone",
       "f":[
        "thumbnail.png",
        "wallWindowStone.mtl",
        "wallWindowStone.obj"
      ]},
      {"d":"wallWood",
       "f":[
        "thumbnail.png",
        "wallWood.mtl",
        "wallWood.obj"
      ]},
      {"d":"wallWoodArch",
       "f":[
        "thumbnail.png",
        "wallWoodArch.mtl",
        "wallWoodArch.obj"
      ]},
      {"d":"wallWoodArchTop",
       "f":[
        "thumbnail.png",
        "wallWoodArchTop.mtl",
        "wallWoodArchTop.obj"
      ]},
      {"d":"wallWoodArchTopDetail",
       "f":[
        "thumbnail.png",
        "wallWoodArchTopDetail.mtl",
        "wallWoodArchTopDetail.obj"
      ]},
      {"d":"wallWoodBlock",
       "f":[
        "thumbnail.png",
        "wallWoodBlock.mtl",
        "wallWoodBlock.obj"
      ]},
      {"d":"wallWoodBlockHalf",
       "f":[
        "thumbnail.png",
        "wallWoodBlockHalf.mtl",
        "wallWoodBlockHalf.obj"
      ]},
      {"d":"wallWoodBroken",
       "f":[
        "thumbnail.png",
        "wallWoodBroken.mtl",
        "wallWoodBroken.obj"
      ]},
      {"d":"wallWoodCorner",
       "f":[
        "thumbnail.png",
        "wallWoodCorner.mtl",
        "wallWoodCorner.obj"
      ]},
      {"d":"wallWoodCornerDiagonal",
       "f":[
        "thumbnail.png",
        "wallWoodCornerDiagonal.mtl",
        "wallWoodCornerDiagonal.obj"
      ]},
      {"d":"wallWoodCornerDiagonalHalf",
       "f":[
        "thumbnail.png",
        "wallWoodCornerDiagonalHalf.mtl",
        "wallWoodCornerDiagonalHalf.obj"
      ]},
      {"d":"wallWoodCornerEdge",
       "f":[
        "thumbnail.png",
        "wallWoodCornerEdge.mtl",
        "wallWoodCornerEdge.obj"
      ]},
      {"d":"wallWoodCurved",
       "f":[
        "thumbnail.png",
        "wallWoodCurved.mtl",
        "wallWoodCurved.obj"
      ]},
      {"d":"wallWoodDetailCross",
       "f":[
        "thumbnail.png",
        "wallWoodDetailCross.mtl",
        "wallWoodDetailCross.obj"
      ]},
      {"d":"wallWoodDetailDiagonal",
       "f":[
        "thumbnail.png",
        "wallWoodDetailDiagonal.mtl",
        "wallWoodDetailDiagonal.obj"
      ]},
      {"d":"wallWoodDetailHorizontal",
       "f":[
        "thumbnail.png",
        "wallWoodDetailHorizontal.mtl",
        "wallWoodDetailHorizontal.obj"
      ]},
      {"d":"wallWoodDiagonal",
       "f":[
        "thumbnail.png",
        "wallWoodDiagonal.mtl",
        "wallWoodDiagonal.obj"
      ]},
      {"d":"wallWoodDoor",
       "f":[
        "thumbnail.png",
        "wallWoodDoor.mtl",
        "wallWoodDoor.obj"
      ]},
      {"d":"wallWoodDoorwayBase",
       "f":[
        "thumbnail.png",
        "wallWoodDoorwayBase.mtl",
        "wallWoodDoorwayBase.obj"
      ]},
      {"d":"wallWoodDoorwayRound",
       "f":[
        "thumbnail.png",
        "wallWoodDoorwayRound.mtl",
        "wallWoodDoorwayRound.obj"
      ]},
      {"d":"wallWoodDoorwaySquare",
       "f":[
        "thumbnail.png",
        "wallWoodDoorwaySquare.mtl",
        "wallWoodDoorwaySquare.obj"
      ]},
      {"d":"wallWoodDoorwaySquareWide",
       "f":[
        "thumbnail.png",
        "wallWoodDoorwaySquareWide.mtl",
        "wallWoodDoorwaySquareWide.obj"
      ]},
      {"d":"wallWoodDoorwaySquareWideCurved",
       "f":[
        "thumbnail.png",
        "wallWoodDoorwaySquareWideCurved.mtl",
        "wallWoodDoorwaySquareWideCurved.obj"
      ]},
      {"d":"wallWoodHalf",
       "f":[
        "thumbnail.png",
        "wallWoodHalf.mtl",
        "wallWoodHalf.obj"
      ]},
      {"d":"wallWoodRounded",
       "f":[
        "thumbnail.png",
        "wallWoodRounded.mtl",
        "wallWoodRounded.obj"
      ]},
      {"d":"wallWoodSide",
       "f":[
        "thumbnail.png",
        "wallWoodSide.mtl",
        "wallWoodSide.obj"
      ]},
      {"d":"wallWoodSlope",
       "f":[
        "thumbnail.png",
        "wallWoodSlope.mtl",
        "wallWoodSlope.obj"
      ]},
      {"d":"wallWoodWindowGlass",
       "f":[
        "thumbnail.png",
        "wallWoodWindowGlass.mtl",
        "wallWoodWindowGlass.obj"
      ]},
      {"d":"wallWoodWindowRound",
       "f":[
        "thumbnail.png",
        "wallWoodWindowRound.mtl",
        "wallWoodWindowRound.obj"
      ]},
      {"d":"wallWoodWindowShutters",
       "f":[
        "thumbnail.png",
        "wallWoodWindowShutters.mtl",
        "wallWoodWindowShutters.obj"
      ]},
      {"d":"wallWoodWindowSmall",
       "f":[
        "thumbnail.png",
        "wallWoodWindowSmall.mtl",
        "wallWoodWindowSmall.obj"
      ]},
      {"d":"wallWoodWindowStone",
       "f":[
        "thumbnail.png",
        "wallWoodWindowStone.mtl",
        "wallWoodWindowStone.obj"
      ]}
    ]},
    {"d":"naturekit-camp-items",
     "f":[
      {"d":"bed",
       "f":[
        "bed.mtl",
        "bed.obj",
        "thumbnail.png"
      ]},
      {"d":"bed_floor",
       "f":[
        "bed_floor.mtl",
        "bed_floor.obj",
        "thumbnail.png"
      ]},
      {"d":"campfire_bricks",
       "f":[
        "campfire_bricks.mtl",
        "campfire_bricks.obj",
        "thumbnail.png"
      ]},
      {"d":"campfire_logs",
       "f":[
        "campfire_logs.mtl",
        "campfire_logs.obj",
        "thumbnail.png"
      ]},
      {"d":"campfire_planks",
       "f":[
        "campfire_planks.mtl",
        "campfire_planks.obj",
        "thumbnail.png"
      ]},
      {"d":"campfire_stones",
       "f":[
        "campfire_stones.mtl",
        "campfire_stones.obj",
        "thumbnail.png"
      ]},
      {"d":"tent_detailedClosed",
       "f":[
        "tent_detailedClosed.mtl",
        "tent_detailedClosed.obj",
        "thumbnail.png"
      ]},
      {"d":"tent_detailedOpen",
       "f":[
        "tent_detailedOpen.mtl",
        "tent_detailedOpen.obj",
        "thumbnail.png"
      ]},
      {"d":"tent_smallClosed",
       "f":[
        "tent_smallClosed.mtl",
        "tent_smallClosed.obj",
        "thumbnail.png"
      ]},
      {"d":"tent_smallOpen",
       "f":[
        "tent_smallOpen.mtl",
        "tent_smallOpen.obj",
        "thumbnail.png"
      ]}
    ]},
    {"d":"naturekit-structures",
     "f":[
      {"d":"bridge_center_stone",
       "f":[
        "bridge_center_stone.mtl",
        "bridge_center_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_center_stoneRound",
       "f":[
        "bridge_center_stoneRound.mtl",
        "bridge_center_stoneRound.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_center_wood",
       "f":[
        "bridge_center_wood.mtl",
        "bridge_center_wood.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_center_woodRound",
       "f":[
        "bridge_center_woodRound.mtl",
        "bridge_center_woodRound.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_side_stone",
       "f":[
        "bridge_side_stone.mtl",
        "bridge_side_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_side_stoneRound",
       "f":[
        "bridge_side_stoneRound.mtl",
        "bridge_side_stoneRound.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_side_wood",
       "f":[
        "bridge_side_wood.mtl",
        "bridge_side_wood.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_side_woodRound",
       "f":[
        "bridge_side_woodRound.mtl",
        "bridge_side_woodRound.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_stone",
       "f":[
        "bridge_stone.mtl",
        "bridge_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_stoneNarrow",
       "f":[
        "bridge_stoneNarrow.mtl",
        "bridge_stoneNarrow.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_stoneRound",
       "f":[
        "bridge_stoneRound.mtl",
        "bridge_stoneRound.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_stoneRoundNarrow",
       "f":[
        "bridge_stoneRoundNarrow.mtl",
        "bridge_stoneRoundNarrow.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_wood",
       "f":[
        "bridge_wood.mtl",
        "bridge_wood.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_woodNarrow",
       "f":[
        "bridge_woodNarrow.mtl",
        "bridge_woodNarrow.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_woodRound",
       "f":[
        "bridge_woodRound.mtl",
        "bridge_woodRound.obj",
        "thumbnail.png"
      ]},
      {"d":"bridge_woodRoundNarrow",
       "f":[
        "bridge_woodRoundNarrow.mtl",
        "bridge_woodRoundNarrow.obj",
        "thumbnail.png"
      ]},
      {"d":"canoe",
       "f":[
        "canoe.mtl",
        "canoe.obj",
        "thumbnail.png"
      ]},
      {"d":"canoe_paddle",
       "f":[
        "canoe_paddle.mtl",
        "canoe_paddle.obj",
        "thumbnail.png"
      ]},
      {"d":"fence_bend",
       "f":[
        "fence_bend.mtl",
        "fence_bend.obj",
        "thumbnail.png"
      ]},
      {"d":"fence_bendCenter",
       "f":[
        "fence_bendCenter.mtl",
        "fence_bendCenter.obj",
        "thumbnail.png"
      ]},
      {"d":"fence_corner",
       "f":[
        "fence_corner.mtl",
        "fence_corner.obj",
        "thumbnail.png"
      ]},
      {"d":"fence_gate",
       "f":[
        "fence_gate.mtl",
        "fence_gate.obj",
        "thumbnail.png"
      ]},
      {"d":"fence_planks",
       "f":[
        "fence_planks.mtl",
        "fence_planks.obj",
        "thumbnail.png"
      ]},
      {"d":"fence_planksDouble",
       "f":[
        "fence_planksDouble.mtl",
        "fence_planksDouble.obj",
        "thumbnail.png"
      ]},
      {"d":"fence_simple",
       "f":[
        "fence_simple.mtl",
        "fence_simple.obj",
        "thumbnail.png"
      ]},
      {"d":"fence_simpleCenter",
       "f":[
        "fence_simpleCenter.mtl",
        "fence_simpleCenter.obj",
        "thumbnail.png"
      ]},
      {"d":"fence_simpleDiagonal",
       "f":[
        "fence_simpleDiagonal.mtl",
        "fence_simpleDiagonal.obj",
        "thumbnail.png"
      ]},
      {"d":"fence_simpleDiagonalCenter",
       "f":[
        "fence_simpleDiagonalCenter.mtl",
        "fence_simpleDiagonalCenter.obj",
        "thumbnail.png"
      ]},
      {"d":"fence_simpleHigh",
       "f":[
        "fence_simpleHigh.mtl",
        "fence_simpleHigh.obj",
        "thumbnail.png"
      ]},
      {"d":"fence_simpleLow",
       "f":[
        "fence_simpleLow.mtl",
        "fence_simpleLow.obj",
        "thumbnail.png"
      ]},
      {"d":"sign",
       "f":[
        "sign.mtl",
        "sign.obj",
        "thumbnail.png"
      ]},
      {"d":"statue_block",
       "f":[
        "statue_block.mtl",
        "statue_block.obj",
        "thumbnail.png"
      ]},
      {"d":"statue_column",
       "f":[
        "statue_column.mtl",
        "statue_column.obj",
        "thumbnail.png"
      ]},
      {"d":"statue_columnDamaged",
       "f":[
        "statue_columnDamaged.mtl",
        "statue_columnDamaged.obj",
        "thumbnail.png"
      ]},
      {"d":"statue_head",
       "f":[
        "statue_head.mtl",
        "statue_head.obj",
        "thumbnail.png"
      ]},
      {"d":"statue_obelisk",
       "f":[
        "statue_obelisk.mtl",
        "statue_obelisk.obj",
        "thumbnail.png"
      ]},
      {"d":"statue_ring",
       "f":[
        "statue_ring.mtl",
        "statue_ring.obj",
        "thumbnail.png"
      ]}
    ]},
    {"d":"naturekit-terrain",
     "f":[
      {"d":"cliff_blockCave_rock",
       "f":[
        "cliff_blockCave_rock.mtl",
        "cliff_blockCave_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockCave_stone",
       "f":[
        "cliff_blockCave_stone.mtl",
        "cliff_blockCave_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockDiagonal_rock",
       "f":[
        "cliff_blockDiagonal_rock.mtl",
        "cliff_blockDiagonal_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockDiagonal_stone",
       "f":[
        "cliff_blockDiagonal_stone.mtl",
        "cliff_blockDiagonal_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockHalf_rock",
       "f":[
        "cliff_blockHalf_rock.mtl",
        "cliff_blockHalf_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockHalf_stone",
       "f":[
        "cliff_blockHalf_stone.mtl",
        "cliff_blockHalf_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockQuarter_rock",
       "f":[
        "cliff_blockQuarter_rock.mtl",
        "cliff_blockQuarter_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockQuarter_stone",
       "f":[
        "cliff_blockQuarter_stone.mtl",
        "cliff_blockQuarter_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockSlopeHalfWalls_rock",
       "f":[
        "cliff_blockSlopeHalfWalls_rock.mtl",
        "cliff_blockSlopeHalfWalls_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockSlopeHalfWalls_stone",
       "f":[
        "cliff_blockSlopeHalfWalls_stone.mtl",
        "cliff_blockSlopeHalfWalls_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockSlopeWalls_rock",
       "f":[
        "cliff_blockSlopeWalls_rock.mtl",
        "cliff_blockSlopeWalls_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockSlopeWalls_stone",
       "f":[
        "cliff_blockSlopeWalls_stone.mtl",
        "cliff_blockSlopeWalls_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockSlope_rock",
       "f":[
        "cliff_blockSlope_rock.mtl",
        "cliff_blockSlope_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_blockSlope_stone",
       "f":[
        "cliff_blockSlope_stone.mtl",
        "cliff_blockSlope_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_block_rock",
       "f":[
        "cliff_block_rock.mtl",
        "cliff_block_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_block_stone",
       "f":[
        "cliff_block_stone.mtl",
        "cliff_block_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_cave_rock",
       "f":[
        "cliff_cave_rock.mtl",
        "cliff_cave_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_cave_stone",
       "f":[
        "cliff_cave_stone.mtl",
        "cliff_cave_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_cornerInnerLarge_rock",
       "f":[
        "cliff_cornerInnerLarge_rock.mtl",
        "cliff_cornerInnerLarge_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_cornerInnerLarge_stone",
       "f":[
        "cliff_cornerInnerLarge_stone.mtl",
        "cliff_cornerInnerLarge_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_cornerInnerTop_rock",
       "f":[
        "cliff_cornerInnerTop_rock.mtl",
        "cliff_cornerInnerTop_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_cornerInnerTop_stone",
       "f":[
        "cliff_cornerInnerTop_stone.mtl",
        "cliff_cornerInnerTop_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_cornerInner_rock",
       "f":[
        "cliff_cornerInner_rock.mtl",
        "cliff_cornerInner_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_cornerInner_stone",
       "f":[
        "cliff_cornerInner_stone.mtl",
        "cliff_cornerInner_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_cornerLarge_rock",
       "f":[
        "cliff_cornerLarge_rock.mtl",
        "cliff_cornerLarge_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_cornerLarge_stone",
       "f":[
        "cliff_cornerLarge_stone.mtl",
        "cliff_cornerLarge_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_cornerTop_rock",
       "f":[
        "cliff_cornerTop_rock.mtl",
        "cliff_cornerTop_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_cornerTop_stone",
       "f":[
        "cliff_cornerTop_stone.mtl",
        "cliff_cornerTop_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_corner_rock",
       "f":[
        "cliff_corner_rock.mtl",
        "cliff_corner_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_corner_stone",
       "f":[
        "cliff_corner_stone.mtl",
        "cliff_corner_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_diagonal_rock",
       "f":[
        "cliff_diagonal_rock.mtl",
        "cliff_diagonal_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_diagonal_stone",
       "f":[
        "cliff_diagonal_stone.mtl",
        "cliff_diagonal_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_halfCornerInner_rock",
       "f":[
        "cliff_halfCornerInner_rock.mtl",
        "cliff_halfCornerInner_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_halfCornerInner_stone",
       "f":[
        "cliff_halfCornerInner_stone.mtl",
        "cliff_halfCornerInner_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_halfCorner_rock",
       "f":[
        "cliff_halfCorner_rock.mtl",
        "cliff_halfCorner_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_halfCorner_stone",
       "f":[
        "cliff_halfCorner_stone.mtl",
        "cliff_halfCorner_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_half_rock",
       "f":[
        "cliff_half_rock.mtl",
        "cliff_half_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_half_stone",
       "f":[
        "cliff_half_stone.mtl",
        "cliff_half_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_large_rock",
       "f":[
        "cliff_large_rock.mtl",
        "cliff_large_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_large_stone",
       "f":[
        "cliff_large_stone.mtl",
        "cliff_large_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_rock",
       "f":[
        "cliff_rock.mtl",
        "cliff_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_stepsCornerInner_rock",
       "f":[
        "cliff_stepsCornerInner_rock.mtl",
        "cliff_stepsCornerInner_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_stepsCornerInner_stone",
       "f":[
        "cliff_stepsCornerInner_stone.mtl",
        "cliff_stepsCornerInner_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_stepsCorner_rock",
       "f":[
        "cliff_stepsCorner_rock.mtl",
        "cliff_stepsCorner_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_stepsCorner_stone",
       "f":[
        "cliff_stepsCorner_stone.mtl",
        "cliff_stepsCorner_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_steps_rock",
       "f":[
        "cliff_steps_rock.mtl",
        "cliff_steps_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_steps_stone",
       "f":[
        "cliff_steps_stone.mtl",
        "cliff_steps_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_stone",
       "f":[
        "cliff_stone.mtl",
        "cliff_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_topDiagonal_rock",
       "f":[
        "cliff_topDiagonal_rock.mtl",
        "cliff_topDiagonal_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_topDiagonal_stone",
       "f":[
        "cliff_topDiagonal_stone.mtl",
        "cliff_topDiagonal_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_top_rock",
       "f":[
        "cliff_top_rock.mtl",
        "cliff_top_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_top_stone",
       "f":[
        "cliff_top_stone.mtl",
        "cliff_top_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_waterfallTop_rock",
       "f":[
        "cliff_waterfallTop_rock.mtl",
        "cliff_waterfallTop_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_waterfallTop_stone",
       "f":[
        "cliff_waterfallTop_stone.mtl",
        "cliff_waterfallTop_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_waterfall_rock",
       "f":[
        "cliff_waterfall_rock.mtl",
        "cliff_waterfall_rock.obj",
        "thumbnail.png"
      ]},
      {"d":"cliff_waterfall_stone",
       "f":[
        "cliff_waterfall_stone.mtl",
        "cliff_waterfall_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathBend",
       "f":[
        "ground_pathBend.mtl",
        "ground_pathBend.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathBendBank",
       "f":[
        "ground_pathBendBank.mtl",
        "ground_pathBendBank.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathCorner",
       "f":[
        "ground_pathCorner.mtl",
        "ground_pathCorner.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathCornerSmall",
       "f":[
        "ground_pathCornerSmall.mtl",
        "ground_pathCornerSmall.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathCross",
       "f":[
        "ground_pathCross.mtl",
        "ground_pathCross.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathEnd",
       "f":[
        "ground_pathEnd.mtl",
        "ground_pathEnd.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathEndClosed",
       "f":[
        "ground_pathEndClosed.mtl",
        "ground_pathEndClosed.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathOpen",
       "f":[
        "ground_pathOpen.mtl",
        "ground_pathOpen.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathRocks",
       "f":[
        "ground_pathRocks.mtl",
        "ground_pathRocks.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathSide",
       "f":[
        "ground_pathSide.mtl",
        "ground_pathSide.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathSideOpen",
       "f":[
        "ground_pathSideOpen.mtl",
        "ground_pathSideOpen.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathSplit",
       "f":[
        "ground_pathSplit.mtl",
        "ground_pathSplit.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathStraight",
       "f":[
        "ground_pathStraight.mtl",
        "ground_pathStraight.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_pathTile",
       "f":[
        "ground_pathTile.mtl",
        "ground_pathTile.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverBend",
       "f":[
        "ground_riverBend.mtl",
        "ground_riverBend.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverBendBank",
       "f":[
        "ground_riverBendBank.mtl",
        "ground_riverBendBank.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverCorner",
       "f":[
        "ground_riverCorner.mtl",
        "ground_riverCorner.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverCornerSmall",
       "f":[
        "ground_riverCornerSmall.mtl",
        "ground_riverCornerSmall.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverCross",
       "f":[
        "ground_riverCross.mtl",
        "ground_riverCross.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverEnd",
       "f":[
        "ground_riverEnd.mtl",
        "ground_riverEnd.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverEndClosed",
       "f":[
        "ground_riverEndClosed.mtl",
        "ground_riverEndClosed.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverOpen",
       "f":[
        "ground_riverOpen.mtl",
        "ground_riverOpen.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverRocks",
       "f":[
        "ground_riverRocks.mtl",
        "ground_riverRocks.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverSide",
       "f":[
        "ground_riverSide.mtl",
        "ground_riverSide.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverSideOpen",
       "f":[
        "ground_riverSideOpen.mtl",
        "ground_riverSideOpen.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverSplit",
       "f":[
        "ground_riverSplit.mtl",
        "ground_riverSplit.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverStraight",
       "f":[
        "ground_riverStraight.mtl",
        "ground_riverStraight.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_riverTile",
       "f":[
        "ground_riverTile.mtl",
        "ground_riverTile.obj",
        "thumbnail.png"
      ]},
      {"d":"path_stone",
       "f":[
        "path_stone.mtl",
        "path_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"path_stoneCircle",
       "f":[
        "path_stoneCircle.mtl",
        "path_stoneCircle.obj",
        "thumbnail.png"
      ]},
      {"d":"path_stoneCorner",
       "f":[
        "path_stoneCorner.mtl",
        "path_stoneCorner.obj",
        "thumbnail.png"
      ]},
      {"d":"path_stoneEnd",
       "f":[
        "path_stoneEnd.mtl",
        "path_stoneEnd.obj",
        "thumbnail.png"
      ]},
      {"d":"path_wood",
       "f":[
        "path_wood.mtl",
        "path_wood.obj",
        "thumbnail.png"
      ]},
      {"d":"path_woodCorner",
       "f":[
        "path_woodCorner.mtl",
        "path_woodCorner.obj",
        "thumbnail.png"
      ]},
      {"d":"path_woodEnd",
       "f":[
        "path_woodEnd.mtl",
        "path_woodEnd.obj",
        "thumbnail.png"
      ]},
      {"d":"platform_beach",
       "f":[
        "platform_beach.mtl",
        "platform_beach.obj",
        "thumbnail.png"
      ]},
      {"d":"platform_grass",
       "f":[
        "platform_grass.mtl",
        "platform_grass.obj",
        "thumbnail.png"
      ]},
      {"d":"platform_stone",
       "f":[
        "platform_stone.mtl",
        "platform_stone.obj",
        "thumbnail.png"
      ]},
      {"d":"pot_large",
       "f":[
        "pot_large.mtl",
        "pot_large.obj",
        "thumbnail.png"
      ]},
      {"d":"pot_small",
       "f":[
        "pot_small.mtl",
        "pot_small.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_largeA",
       "f":[
        "rock_largeA.mtl",
        "rock_largeA.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_largeB",
       "f":[
        "rock_largeB.mtl",
        "rock_largeB.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_largeC",
       "f":[
        "rock_largeC.mtl",
        "rock_largeC.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_largeD",
       "f":[
        "rock_largeD.mtl",
        "rock_largeD.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_largeE",
       "f":[
        "rock_largeE.mtl",
        "rock_largeE.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_largeF",
       "f":[
        "rock_largeF.mtl",
        "rock_largeF.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallA",
       "f":[
        "rock_smallA.mtl",
        "rock_smallA.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallB",
       "f":[
        "rock_smallB.mtl",
        "rock_smallB.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallC",
       "f":[
        "rock_smallC.mtl",
        "rock_smallC.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallD",
       "f":[
        "rock_smallD.mtl",
        "rock_smallD.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallE",
       "f":[
        "rock_smallE.mtl",
        "rock_smallE.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallF",
       "f":[
        "rock_smallF.mtl",
        "rock_smallF.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallFlatA",
       "f":[
        "rock_smallFlatA.mtl",
        "rock_smallFlatA.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallFlatB",
       "f":[
        "rock_smallFlatB.mtl",
        "rock_smallFlatB.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallFlatC",
       "f":[
        "rock_smallFlatC.mtl",
        "rock_smallFlatC.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallG",
       "f":[
        "rock_smallG.mtl",
        "rock_smallG.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallH",
       "f":[
        "rock_smallH.mtl",
        "rock_smallH.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallI",
       "f":[
        "rock_smallI.mtl",
        "rock_smallI.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallTopA",
       "f":[
        "rock_smallTopA.mtl",
        "rock_smallTopA.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_smallTopB",
       "f":[
        "rock_smallTopB.mtl",
        "rock_smallTopB.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_tallA",
       "f":[
        "rock_tallA.mtl",
        "rock_tallA.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_tallB",
       "f":[
        "rock_tallB.mtl",
        "rock_tallB.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_tallC",
       "f":[
        "rock_tallC.mtl",
        "rock_tallC.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_tallD",
       "f":[
        "rock_tallD.mtl",
        "rock_tallD.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_tallE",
       "f":[
        "rock_tallE.mtl",
        "rock_tallE.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_tallF",
       "f":[
        "rock_tallF.mtl",
        "rock_tallF.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_tallG",
       "f":[
        "rock_tallG.mtl",
        "rock_tallG.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_tallH",
       "f":[
        "rock_tallH.mtl",
        "rock_tallH.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_tallI",
       "f":[
        "rock_tallI.mtl",
        "rock_tallI.obj",
        "thumbnail.png"
      ]},
      {"d":"rock_tallJ",
       "f":[
        "rock_tallJ.mtl",
        "rock_tallJ.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_largeA",
       "f":[
        "stone_largeA.mtl",
        "stone_largeA.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_largeB",
       "f":[
        "stone_largeB.mtl",
        "stone_largeB.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_largeC",
       "f":[
        "stone_largeC.mtl",
        "stone_largeC.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_largeD",
       "f":[
        "stone_largeD.mtl",
        "stone_largeD.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_largeE",
       "f":[
        "stone_largeE.mtl",
        "stone_largeE.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_largeF",
       "f":[
        "stone_largeF.mtl",
        "stone_largeF.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallA",
       "f":[
        "stone_smallA.mtl",
        "stone_smallA.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallB",
       "f":[
        "stone_smallB.mtl",
        "stone_smallB.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallC",
       "f":[
        "stone_smallC.mtl",
        "stone_smallC.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallD",
       "f":[
        "stone_smallD.mtl",
        "stone_smallD.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallE",
       "f":[
        "stone_smallE.mtl",
        "stone_smallE.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallF",
       "f":[
        "stone_smallF.mtl",
        "stone_smallF.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallFlatA",
       "f":[
        "stone_smallFlatA.mtl",
        "stone_smallFlatA.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallFlatB",
       "f":[
        "stone_smallFlatB.mtl",
        "stone_smallFlatB.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallFlatC",
       "f":[
        "stone_smallFlatC.mtl",
        "stone_smallFlatC.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallG",
       "f":[
        "stone_smallG.mtl",
        "stone_smallG.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallH",
       "f":[
        "stone_smallH.mtl",
        "stone_smallH.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallI",
       "f":[
        "stone_smallI.mtl",
        "stone_smallI.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallTopA",
       "f":[
        "stone_smallTopA.mtl",
        "stone_smallTopA.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_smallTopB",
       "f":[
        "stone_smallTopB.mtl",
        "stone_smallTopB.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_tallA",
       "f":[
        "stone_tallA.mtl",
        "stone_tallA.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_tallB",
       "f":[
        "stone_tallB.mtl",
        "stone_tallB.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_tallC",
       "f":[
        "stone_tallC.mtl",
        "stone_tallC.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_tallD",
       "f":[
        "stone_tallD.mtl",
        "stone_tallD.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_tallE",
       "f":[
        "stone_tallE.mtl",
        "stone_tallE.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_tallF",
       "f":[
        "stone_tallF.mtl",
        "stone_tallF.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_tallG",
       "f":[
        "stone_tallG.mtl",
        "stone_tallG.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_tallH",
       "f":[
        "stone_tallH.mtl",
        "stone_tallH.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_tallI",
       "f":[
        "stone_tallI.mtl",
        "stone_tallI.obj",
        "thumbnail.png"
      ]},
      {"d":"stone_tallJ",
       "f":[
        "stone_tallJ.mtl",
        "stone_tallJ.obj",
        "thumbnail.png"
      ]}
    ]},
    {"d":"naturekit-vegetation",
     "f":[
      {"d":"cactus_short",
       "f":[
        "cactus_short.mtl",
        "cactus_short.obj",
        "thumbnail.png"
      ]},
      {"d":"cactus_tall",
       "f":[
        "cactus_tall.mtl",
        "cactus_tall.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_bambooStageA",
       "f":[
        "crops_bambooStageA.mtl",
        "crops_bambooStageA.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_bambooStageB",
       "f":[
        "crops_bambooStageB.mtl",
        "crops_bambooStageB.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_cornStageA",
       "f":[
        "crops_cornStageA.mtl",
        "crops_cornStageA.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_cornStageB",
       "f":[
        "crops_cornStageB.mtl",
        "crops_cornStageB.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_cornStageC",
       "f":[
        "crops_cornStageC.mtl",
        "crops_cornStageC.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_cornStageD",
       "f":[
        "crops_cornStageD.mtl",
        "crops_cornStageD.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_dirtDoubleRow",
       "f":[
        "crops_dirtDoubleRow.mtl",
        "crops_dirtDoubleRow.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_dirtDoubleRowCorner",
       "f":[
        "crops_dirtDoubleRowCorner.mtl",
        "crops_dirtDoubleRowCorner.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_dirtDoubleRowEnd",
       "f":[
        "crops_dirtDoubleRowEnd.mtl",
        "crops_dirtDoubleRowEnd.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_dirtRow",
       "f":[
        "crops_dirtRow.mtl",
        "crops_dirtRow.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_dirtRowCorner",
       "f":[
        "crops_dirtRowCorner.mtl",
        "crops_dirtRowCorner.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_dirtRowEnd",
       "f":[
        "crops_dirtRowEnd.mtl",
        "crops_dirtRowEnd.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_dirtSingle",
       "f":[
        "crops_dirtSingle.mtl",
        "crops_dirtSingle.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_leafsStageA",
       "f":[
        "crops_leafsStageA.mtl",
        "crops_leafsStageA.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_leafsStageB",
       "f":[
        "crops_leafsStageB.mtl",
        "crops_leafsStageB.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_wheatStageA",
       "f":[
        "crops_wheatStageA.mtl",
        "crops_wheatStageA.obj",
        "thumbnail.png"
      ]},
      {"d":"crops_wheatStageB",
       "f":[
        "crops_wheatStageB.mtl",
        "crops_wheatStageB.obj",
        "thumbnail.png"
      ]},
      {"d":"crop_carrot",
       "f":[
        "crop_carrot.mtl",
        "crop_carrot.obj",
        "thumbnail.png"
      ]},
      {"d":"crop_melon",
       "f":[
        "crop_melon.mtl",
        "crop_melon.obj",
        "thumbnail.png"
      ]},
      {"d":"crop_pumpkin",
       "f":[
        "crop_pumpkin.mtl",
        "crop_pumpkin.obj",
        "thumbnail.png"
      ]},
      {"d":"crop_turnip",
       "f":[
        "crop_turnip.mtl",
        "crop_turnip.obj",
        "thumbnail.png"
      ]},
      {"d":"flower_purpleA",
       "f":[
        "flower_purpleA.mtl",
        "flower_purpleA.obj",
        "thumbnail.png"
      ]},
      {"d":"flower_purpleB",
       "f":[
        "flower_purpleB.mtl",
        "flower_purpleB.obj",
        "thumbnail.png"
      ]},
      {"d":"flower_purpleC",
       "f":[
        "flower_purpleC.mtl",
        "flower_purpleC.obj",
        "thumbnail.png"
      ]},
      {"d":"flower_redA",
       "f":[
        "flower_redA.mtl",
        "flower_redA.obj",
        "thumbnail.png"
      ]},
      {"d":"flower_redB",
       "f":[
        "flower_redB.mtl",
        "flower_redB.obj",
        "thumbnail.png"
      ]},
      {"d":"flower_redC",
       "f":[
        "flower_redC.mtl",
        "flower_redC.obj",
        "thumbnail.png"
      ]},
      {"d":"flower_yellowA",
       "f":[
        "flower_yellowA.mtl",
        "flower_yellowA.obj",
        "thumbnail.png"
      ]},
      {"d":"flower_yellowB",
       "f":[
        "flower_yellowB.mtl",
        "flower_yellowB.obj",
        "thumbnail.png"
      ]},
      {"d":"flower_yellowC",
       "f":[
        "flower_yellowC.mtl",
        "flower_yellowC.obj",
        "thumbnail.png"
      ]},
      {"d":"grass",
       "f":[
        "grass.mtl",
        "grass.obj",
        "thumbnail.png"
      ]},
      {"d":"grass_large",
       "f":[
        "grass_large.mtl",
        "grass_large.obj",
        "thumbnail.png"
      ]},
      {"d":"grass_leafs",
       "f":[
        "grass_leafs.mtl",
        "grass_leafs.obj",
        "thumbnail.png"
      ]},
      {"d":"grass_leafsLarge",
       "f":[
        "grass_leafsLarge.mtl",
        "grass_leafsLarge.obj",
        "thumbnail.png"
      ]},
      {"d":"ground_grass",
       "f":[
        "ground_grass.mtl",
        "ground_grass.obj",
        "thumbnail.png"
      ]},
      {"d":"hanging_moss",
       "f":[
        "hanging_moss.mtl",
        "hanging_moss.obj",
        "thumbnail.png"
      ]},
      {"d":"lily_large",
       "f":[
        "lily_large.mtl",
        "lily_large.obj",
        "thumbnail.png"
      ]},
      {"d":"lily_small",
       "f":[
        "lily_small.mtl",
        "lily_small.obj",
        "thumbnail.png"
      ]},
      {"d":"log",
       "f":[
        "log.mtl",
        "log.obj",
        "thumbnail.png"
      ]},
      {"d":"log_large",
       "f":[
        "log_large.mtl",
        "log_large.obj",
        "thumbnail.png"
      ]},
      {"d":"log_stack",
       "f":[
        "log_stack.mtl",
        "log_stack.obj",
        "thumbnail.png"
      ]},
      {"d":"log_stackLarge",
       "f":[
        "log_stackLarge.mtl",
        "log_stackLarge.obj",
        "thumbnail.png"
      ]},
      {"d":"mushroom_red",
       "f":[
        "mushroom_red.mtl",
        "mushroom_red.obj",
        "thumbnail.png"
      ]},
      {"d":"mushroom_redGroup",
       "f":[
        "mushroom_redGroup.mtl",
        "mushroom_redGroup.obj",
        "thumbnail.png"
      ]},
      {"d":"mushroom_redTall",
       "f":[
        "mushroom_redTall.mtl",
        "mushroom_redTall.obj",
        "thumbnail.png"
      ]},
      {"d":"mushroom_tan",
       "f":[
        "mushroom_tan.mtl",
        "mushroom_tan.obj",
        "thumbnail.png"
      ]},
      {"d":"mushroom_tanGroup",
       "f":[
        "mushroom_tanGroup.mtl",
        "mushroom_tanGroup.obj",
        "thumbnail.png"
      ]},
      {"d":"mushroom_tanTall",
       "f":[
        "mushroom_tanTall.mtl",
        "mushroom_tanTall.obj",
        "thumbnail.png"
      ]},
      {"d":"plant_bush",
       "f":[
        "plant_bush.mtl",
        "plant_bush.obj",
        "thumbnail.png"
      ]},
      {"d":"plant_bushDetailed",
       "f":[
        "plant_bushDetailed.mtl",
        "plant_bushDetailed.obj",
        "thumbnail.png"
      ]},
      {"d":"plant_bushLarge",
       "f":[
        "plant_bushLarge.mtl",
        "plant_bushLarge.obj",
        "thumbnail.png"
      ]},
      {"d":"plant_bushLargeTriangle",
       "f":[
        "plant_bushLargeTriangle.mtl",
        "plant_bushLargeTriangle.obj",
        "thumbnail.png"
      ]},
      {"d":"plant_bushSmall",
       "f":[
        "plant_bushSmall.mtl",
        "plant_bushSmall.obj",
        "thumbnail.png"
      ]},
      {"d":"plant_bushTriangle",
       "f":[
        "plant_bushTriangle.mtl",
        "plant_bushTriangle.obj",
        "thumbnail.png"
      ]},
      {"d":"plant_flatShort",
       "f":[
        "plant_flatShort.mtl",
        "plant_flatShort.obj",
        "thumbnail.png"
      ]},
      {"d":"plant_flatTall",
       "f":[
        "plant_flatTall.mtl",
        "plant_flatTall.obj",
        "thumbnail.png"
      ]},
      {"d":"stump_old",
       "f":[
        "stump_old.mtl",
        "stump_old.obj",
        "thumbnail.png"
      ]},
      {"d":"stump_oldTall",
       "f":[
        "stump_oldTall.mtl",
        "stump_oldTall.obj",
        "thumbnail.png"
      ]},
      {"d":"stump_round",
       "f":[
        "stump_round.mtl",
        "stump_round.obj",
        "thumbnail.png"
      ]},
      {"d":"stump_roundDetailed",
       "f":[
        "stump_roundDetailed.mtl",
        "stump_roundDetailed.obj",
        "thumbnail.png"
      ]},
      {"d":"stump_square",
       "f":[
        "stump_square.mtl",
        "stump_square.obj",
        "thumbnail.png"
      ]},
      {"d":"stump_squareDetailed",
       "f":[
        "stump_squareDetailed.mtl",
        "stump_squareDetailed.obj",
        "thumbnail.png"
      ]},
      {"d":"stump_squareDetailedWide",
       "f":[
        "stump_squareDetailedWide.mtl",
        "stump_squareDetailedWide.obj",
        "thumbnail.png"
      ]},
      {"d":"tree_blocks",
       "f":[
        "thumbnail.png",
        "tree_blocks.mtl",
        "tree_blocks.obj"
      ]},
      {"d":"tree_blocks_dark",
       "f":[
        "thumbnail.png",
        "tree_blocks_dark.mtl",
        "tree_blocks_dark.obj"
      ]},
      {"d":"tree_blocks_fall",
       "f":[
        "thumbnail.png",
        "tree_blocks_fall.mtl",
        "tree_blocks_fall.obj"
      ]},
      {"d":"tree_cone",
       "f":[
        "thumbnail.png",
        "tree_cone.mtl",
        "tree_cone.obj"
      ]},
      {"d":"tree_cone_dark",
       "f":[
        "thumbnail.png",
        "tree_cone_dark.mtl",
        "tree_cone_dark.obj"
      ]},
      {"d":"tree_cone_fall",
       "f":[
        "thumbnail.png",
        "tree_cone_fall.mtl",
        "tree_cone_fall.obj"
      ]},
      {"d":"tree_default",
       "f":[
        "thumbnail.png",
        "tree_default.mtl",
        "tree_default.obj"
      ]},
      {"d":"tree_default_dark",
       "f":[
        "thumbnail.png",
        "tree_default_dark.mtl",
        "tree_default_dark.obj"
      ]},
      {"d":"tree_default_fall",
       "f":[
        "thumbnail.png",
        "tree_default_fall.mtl",
        "tree_default_fall.obj"
      ]},
      {"d":"tree_detailed",
       "f":[
        "thumbnail.png",
        "tree_detailed.mtl",
        "tree_detailed.obj"
      ]},
      {"d":"tree_detailed_dark",
       "f":[
        "thumbnail.png",
        "tree_detailed_dark.mtl",
        "tree_detailed_dark.obj"
      ]},
      {"d":"tree_detailed_fall",
       "f":[
        "thumbnail.png",
        "tree_detailed_fall.mtl",
        "tree_detailed_fall.obj"
      ]},
      {"d":"tree_fat",
       "f":[
        "thumbnail.png",
        "tree_fat.mtl",
        "tree_fat.obj"
      ]},
      {"d":"tree_fat_darkh",
       "f":[
        "thumbnail.png",
        "tree_fat_darkh.mtl",
        "tree_fat_darkh.obj"
      ]},
      {"d":"tree_fat_fall",
       "f":[
        "thumbnail.png",
        "tree_fat_fall.mtl",
        "tree_fat_fall.obj"
      ]},
      {"d":"tree_oak",
       "f":[
        "thumbnail.png",
        "tree_oak.mtl",
        "tree_oak.obj"
      ]},
      {"d":"tree_oak_dark",
       "f":[
        "thumbnail.png",
        "tree_oak_dark.mtl",
        "tree_oak_dark.obj"
      ]},
      {"d":"tree_oak_fall",
       "f":[
        "thumbnail.png",
        "tree_oak_fall.mtl",
        "tree_oak_fall.obj"
      ]},
      {"d":"tree_palm",
       "f":[
        "thumbnail.png",
        "tree_palm.mtl",
        "tree_palm.obj"
      ]},
      {"d":"tree_palmBend",
       "f":[
        "thumbnail.png",
        "tree_palmBend.mtl",
        "tree_palmBend.obj"
      ]},
      {"d":"tree_palmDetailedShort",
       "f":[
        "thumbnail.png",
        "tree_palmDetailedShort.mtl",
        "tree_palmDetailedShort.obj"
      ]},
      {"d":"tree_palmDetailedTall",
       "f":[
        "thumbnail.png",
        "tree_palmDetailedTall.mtl",
        "tree_palmDetailedTall.obj"
      ]},
      {"d":"tree_palmShort",
       "f":[
        "thumbnail.png",
        "tree_palmShort.mtl",
        "tree_palmShort.obj"
      ]},
      {"d":"tree_palmTall",
       "f":[
        "thumbnail.png",
        "tree_palmTall.mtl",
        "tree_palmTall.obj"
      ]},
      {"d":"tree_pineDefaultA",
       "f":[
        "thumbnail.png",
        "tree_pineDefaultA.mtl",
        "tree_pineDefaultA.obj"
      ]},
      {"d":"tree_pineDefaultB",
       "f":[
        "thumbnail.png",
        "tree_pineDefaultB.mtl",
        "tree_pineDefaultB.obj"
      ]},
      {"d":"tree_pineGroundA",
       "f":[
        "thumbnail.png",
        "tree_pineGroundA.mtl",
        "tree_pineGroundA.obj"
      ]},
      {"d":"tree_pineGroundB",
       "f":[
        "thumbnail.png",
        "tree_pineGroundB.mtl",
        "tree_pineGroundB.obj"
      ]},
      {"d":"tree_pineRoundA",
       "f":[
        "thumbnail.png",
        "tree_pineRoundA.mtl",
        "tree_pineRoundA.obj"
      ]},
      {"d":"tree_pineRoundB",
       "f":[
        "thumbnail.png",
        "tree_pineRoundB.mtl",
        "tree_pineRoundB.obj"
      ]},
      {"d":"tree_pineRoundC",
       "f":[
        "thumbnail.png",
        "tree_pineRoundC.mtl",
        "tree_pineRoundC.obj"
      ]},
      {"d":"tree_pineRoundD",
       "f":[
        "thumbnail.png",
        "tree_pineRoundD.mtl",
        "tree_pineRoundD.obj"
      ]},
      {"d":"tree_pineRoundE",
       "f":[
        "thumbnail.png",
        "tree_pineRoundE.mtl",
        "tree_pineRoundE.obj"
      ]},
      {"d":"tree_pineRoundF",
       "f":[
        "thumbnail.png",
        "tree_pineRoundF.mtl",
        "tree_pineRoundF.obj"
      ]},
      {"d":"tree_pineSmallA",
       "f":[
        "thumbnail.png",
        "tree_pineSmallA.mtl",
        "tree_pineSmallA.obj"
      ]},
      {"d":"tree_pineSmallB",
       "f":[
        "thumbnail.png",
        "tree_pineSmallB.mtl",
        "tree_pineSmallB.obj"
      ]},
      {"d":"tree_pineSmallC",
       "f":[
        "thumbnail.png",
        "tree_pineSmallC.mtl",
        "tree_pineSmallC.obj"
      ]},
      {"d":"tree_pineSmallD",
       "f":[
        "thumbnail.png",
        "tree_pineSmallD.mtl",
        "tree_pineSmallD.obj"
      ]},
      {"d":"tree_pineTallA",
       "f":[
        "thumbnail.png",
        "tree_pineTallA.mtl",
        "tree_pineTallA.obj"
      ]},
      {"d":"tree_pineTallA_detailed",
       "f":[
        "thumbnail.png",
        "tree_pineTallA_detailed.mtl",
        "tree_pineTallA_detailed.obj"
      ]},
      {"d":"tree_pineTallB",
       "f":[
        "thumbnail.png",
        "tree_pineTallB.mtl",
        "tree_pineTallB.obj"
      ]},
      {"d":"tree_pineTallB_detailed",
       "f":[
        "thumbnail.png",
        "tree_pineTallB_detailed.mtl",
        "tree_pineTallB_detailed.obj"
      ]},
      {"d":"tree_pineTallC",
       "f":[
        "thumbnail.png",
        "tree_pineTallC.mtl",
        "tree_pineTallC.obj"
      ]},
      {"d":"tree_pineTallC_detailed",
       "f":[
        "thumbnail.png",
        "tree_pineTallC_detailed.mtl",
        "tree_pineTallC_detailed.obj"
      ]},
      {"d":"tree_pineTallD",
       "f":[
        "thumbnail.png",
        "tree_pineTallD.mtl",
        "tree_pineTallD.obj"
      ]},
      {"d":"tree_pineTallD_detailed",
       "f":[
        "thumbnail.png",
        "tree_pineTallD_detailed.mtl",
        "tree_pineTallD_detailed.obj"
      ]},
      {"d":"tree_plateau",
       "f":[
        "thumbnail.png",
        "tree_plateau.mtl",
        "tree_plateau.obj"
      ]},
      {"d":"tree_plateau_dark",
       "f":[
        "thumbnail.png",
        "tree_plateau_dark.mtl",
        "tree_plateau_dark.obj"
      ]},
      {"d":"tree_plateau_fall",
       "f":[
        "thumbnail.png",
        "tree_plateau_fall.mtl",
        "tree_plateau_fall.obj"
      ]},
      {"d":"tree_simple",
       "f":[
        "thumbnail.png",
        "tree_simple.mtl",
        "tree_simple.obj"
      ]},
      {"d":"tree_simple_dark",
       "f":[
        "thumbnail.png",
        "tree_simple_dark.mtl",
        "tree_simple_dark.obj"
      ]},
      {"d":"tree_simple_fall",
       "f":[
        "thumbnail.png",
        "tree_simple_fall.mtl",
        "tree_simple_fall.obj"
      ]},
      {"d":"tree_small",
       "f":[
        "thumbnail.png",
        "tree_small.mtl",
        "tree_small.obj"
      ]},
      {"d":"tree_small_dark",
       "f":[
        "thumbnail.png",
        "tree_small_dark.mtl",
        "tree_small_dark.obj"
      ]},
      {"d":"tree_small_fall",
       "f":[
        "thumbnail.png",
        "tree_small_fall.mtl",
        "tree_small_fall.obj"
      ]},
      {"d":"tree_tall",
       "f":[
        "thumbnail.png",
        "tree_tall.mtl",
        "tree_tall.obj"
      ]},
      {"d":"tree_tall_dark",
       "f":[
        "thumbnail.png",
        "tree_tall_dark.mtl",
        "tree_tall_dark.obj"
      ]},
      {"d":"tree_tall_fall",
       "f":[
        "thumbnail.png",
        "tree_tall_fall.mtl",
        "tree_tall_fall.obj"
      ]},
      {"d":"tree_thin",
       "f":[
        "tree_thin.mtl",
        "tree_thin.obj"
      ]},
      {"d":"tree_thin_dark",
       "f":[
        "thumbnail.png",
        "tree_thin_dark.mtl",
        "tree_thin_dark.obj"
      ]},
      {"d":"tree_thin_fall",
       "f":[
        "thumbnail.png",
        "tree_thin_fall.mtl",
        "tree_thin_fall.obj"
      ]}
    ]},
    {"d":"skyboxes",
     "f":[
      {"d":"city",
       "f":[
        "city_nx.jpg",
        "city_ny.jpg",
        "city_nz.jpg",
        "city_px.jpg",
        "city_py.jpg",
        "city_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"desert",
       "f":[
        "desert_nx.jpg",
        "desert_ny.jpg",
        "desert_nz.jpg",
        "desert_px.jpg",
        "desert_py.jpg",
        "desert_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"dusk",
       "f":[
        "dusk_nx.jpg",
        "dusk_ny.jpg",
        "dusk_nz.jpg",
        "dusk_px.jpg",
        "dusk_py.jpg",
        "dusk_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"hilly",
       "f":[
        "hilly_nx.jpg",
        "hilly_ny.jpg",
        "hilly_nz.jpg",
        "hilly_px.jpg",
        "hilly_py.jpg",
        "hilly_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"hot",
       "f":[
        "hot_nx.jpg",
        "hot_ny.jpg",
        "hot_nz.jpg",
        "hot_px.jpg",
        "hot_py.jpg",
        "hot_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"moon",
       "f":[
        "moon_nx.jpg",
        "moon_ny.jpg",
        "moon_nz.jpg",
        "moon_px.jpg",
        "moon_py.jpg",
        "moon_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"none",
       "f":[
        "thumbnail.png"
      ]},
      {"d":"rain",
       "f":[
        "rain_nx.jpg",
        "rain_ny.jpg",
        "rain_nz.jpg",
        "rain_px.jpg",
        "rain_py.jpg",
        "rain_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"snow1",
       "f":[
        "snow1_nx.jpg",
        "snow1_ny.jpg",
        "snow1_nz.jpg",
        "snow1_px.jpg",
        "snow1_py.jpg",
        "snow1_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"TropicalSunnyDay",
       "f":[
        "thumbnail.png",
        "TropicalSunnyDay_nx.jpg",
        "TropicalSunnyDay_ny.jpg",
        "TropicalSunnyDay_nz.jpg",
        "TropicalSunnyDay_px.jpg",
        "TropicalSunnyDay_py.jpg",
        "TropicalSunnyDay_pz.jpg"
      ]}
    ]}
  ]},
  {"d":"html",
   "f":[
    "introScreen.html",
    "kenney-fantasy-town-kit.jpg",
    "kenney_natureKit_2.1.jpg"
  ]}
]